### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by Yajo** [pykong/copier#112]
Would you mind releasing 3.0.0?

I really need all new features! And about #111, it can land later as a 3.1.0 without problem IMHO.

TODO:

- [ ] Finish https://github.com/Tecnativa/doodba-scaffolding/pull/69. Once it's green and finished, it means copier 3.0.0 is good to be released, as it leverages all new features.

**Comment by pykong** [comment]
@Yajo Thank for your continuing contributions to `copier`. You are really moving it forward.
I am going to release next weekend as I will still need to up a couple of things in this respect.

**Comment by Yajo** [comment]
Well, actually I'm still developing my template, so I'm not in a hurry for the new version yet.

**Comment by pykong** [comment]
@Yajo I am still struggling to flange GitHub Actions to PyPI.
(This would be the first package I am publishing myself to PyPI.)

Hence, I am afraid I won't be able to publish this weekend, as I have initially prospected.

**Comment by Yajo** [comment]
No problem, I'm still refactoring my scaffolding to copier (https://github.com/Tecnativa/doodba-scaffolding/pull/69 if you're curious) and I might find some rough edges.

I'd suggest to publish something like copier 3.0.0a0, to avoid publishing it as stable after so many changes.

**Comment by pykong** [comment]
@Yajo I have just established the uplink to Test-PyPI and PyPI.
A new version will be published automatically whenever a new release is crafted.
(Import: The version in the `pyproject.toml` needs to be upper or lese PyPI will reject the upload!)

I am closing this issue as there is nothing actionable left in here.
