### ISSUE TITLE
Include additional folder and files

### ISSUE THREAD

**Issue by pykong** [pykong/copier#116]
I am considering closing my smoldring **PR** #79 in favour of a simpler and more robust way for including files outside the template folder.

I was think along the lines of:

```yaml
_incude_extra_paths:
    - "../my_awesome_file.txt"
     - "../my_awesome_folder/"
```
**Note:** This is different to the already present `extra_paths` setting which allows to specify additional lookup paths for Jinja templates.

Will then be copied over to the destination folder, after (or before?) Jinja rendering has occured.
Would we need to allow specifying the exact location within the destination, as well?

@Yajo What do you think? Coud you see use in this feature?

**Comment by Yajo** [comment]
This seems to be a feature more targeted to raw copies usage.

My big interest is in git templates though. In those cases, you can use git submodules, and you can use jinja's `{% extend %}` to extend templates or blocks from those submodules, so for my use case that'd be just enough, if I'm understanding this well.

**Comment by pykong** [comment]
I am not pursuing this for now. Because: YAGNI

However, we might still have git templates:
@Yajo I have never heard of git templates before.
Is this something you can make a **PR** before the next release?

**Comment by Yajo** [comment]
what do you mean with git templates?

**Comment by pykong** [comment]
@Yajo I am quoting you from https://github.com/pykong/copier/issues/116#issuecomment-588116030, emphasis added by me.

> [...]
> My big interest is in **git templates** though.
> [...]

**Comment by Yajo** [comment]
Oh I meant templates that are git-tracked, not templates that are simple folders in a filesystem.

**Comment by pykong** [comment]
I am closing this, as I am not going to implement some raw copy feature for `3.0.0.`.
It can be emulated via the task runner if necessary albeit it would somehow defeat the purpose of Copier being a templating tool. 

@Yajo Feel free to reopen if you have a different idea here.
