### ISSUE TITLE
Transclude other YAML files

### ISSUE THREAD

**Issue by pykong** [pykong/copier#117]
As already described in #116, I like to think up a simpler and more robust way than **PR** #79.

**I like to have a way to reuse settings across projects.**
For example most of my projects run an identical chain of commands _(e.g. start VE, init git, etc. ...)_.

Instead of allowing some complex folder inheritance as proposed by **PR** #79, which potentially opens a can of worms with many unknown side effects, simply allowing to reference other yaml files and their settings would cover most my use cases.

Potential ways to accomplish this are described here:
https://stackoverflow.com/questions/528281/how-can-i-include-a-yaml-file-inside-another

Or we employ Jinja for this purpose as well. That would make sense, as we are already including other files via Jinja.

**Comment by Yajo** [comment]
One solution would be to allow jinja inside `copier.yml` itself, but that'd be a simplified jinja that wouldn't include variables that will be later obtained from `copier.yml` itself.

Another solution would be to add a `_include_manifests:` key, which lets you include other files such as `copier.01.yml`, `copier.02.yml`, etc. All those get merged in order, and the final result is used as a single `copier.yml` file.

We really need #110 fixed, or it will keep complicating everything... :thinking:
