### ISSUE TITLE
ImportError: cannot import name 'copier' from 'plumbum.cmd' 

### ISSUE THREAD

**Issue by pykong** [pykong/copier#133]
@Yajo I believe I have introduced a bug and it slipped through my testing.

`pytest` is failing with two tests with the following error message:
`ImportError: cannot import name 'copier' from 'plumbum.cmd' `

See whole log:
https://github.com/pykong/copier/runs/470981437#step:7:1

I was so far unable to triage it, do you got any idea?

**Comment by Yajo** [comment]
I'd say it's a problem with $PATH, which maybe doesn't include `.venv/bin`.

Try prefixing the test task with `env PATH="./.venv/bin:$PATH` in the action file.
