### ISSUE TITLE
Release 3.0.0

### ISSUE THREAD

**Issue by pykong** [pykong/copier#150]
This is to track the remaining issues before releasing copier `3.0.0`.

An overview of currently open issues that need to be closed before releasing can be found by clicking on the link below:

[Milestone 3.0.0](https://github.com/pykong/copier/milestones/3.0.0)

**Comment by Yajo** [comment]
I just upgraded latest release to beta. It seems feature complete, I just want to do some real world usage before releasing stable.

**Comment by Yajo** [comment]
Well, all my tests are OK.

It seems to me like it's time to do the release. Wanna do it yourself?

**Comment by pykong** [comment]
The publishing process failed.
I won't have the time to look into before the next weekend.

**Comment by pykong** [comment]
OK. "[...] practicality beats purity." So, I simply released as v3.0.1.

@Yajo Good job and thanks for your continued zest pushing the boundaries of this project!

Now we have finally released v3 it is actually time for a big release party, unfortunately right npw, corona forbids such. Another time then. :-)
