### ISSUE TITLE
inter-hunk-context=-1 under Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by theangryangel** [pykong/copier#175]
Not sure if this is a problem or not. I guess it depends what versions of git copier supports.

Ubuntu 18.04 LTS ships with git 2.17.1 by default. 

The call change to git diff in 6d7ab7f94198a7fa16c899ef709215fb2d218de3 to use `--inter-hunk-context=-1` results in copier erroring due to an invalid arg. Looks like it's unhappy with -1.

Updating to the latest via PPA is relatively straight forward. Just wanted to raise it incase anyone else was having issues and secondly if this is something copier wants to work around.

**Comment by Yajo** [comment]
Yes, @chienandalu today experienced the same.

The fact is that if you don't update git, so that it supports such parameter, you'll get weird results with your updates.

Let me add a workaround for this. I'll just disable that flag and warn the user if git is old.
