### ISSUE TITLE
Use a subdirectory

### ISSUE THREAD

**Issue by pawamoy** [pykong/copier#183]
Often times a template is wrapped in a subdirectory of your repository, because there are files you do not want to include into the template, or scripts for updating contents, etc.

Examples:
  - README: you want to explain what is your template, how to generate a project from it, how to use the generated project, etc. This does not belong to the template itself
  - LICENSE: your template is licensed, but the user might not want to use the same license in the generated project.

So my question is: is it possible to render only a subdirectory of the git repository specified as source?

I tried defining `_src_path` in `copiers.yml` but it had no effect.

**Comment by Yajo** [comment]
> is it possible to render only a subdirectory of the git repository specified as source?

Right now it's not possible.

Keep in mind that you can get what you want with a combination of `_exclude` and `.tmpl` in your template.

Take a look at [doodba-copier-template](https://github.com/Tecnativa/doodba-copier-template/tree/339d9589a2213e521a2a85b174b51b3bfdf23513), and notice a few things:

- There's a `README.md` file and a `README.md.jinja` file (in that template I use `.jinja` as templates suffix). In such case, copier automatically ignores `README.md`, and that's a tested feature of copier.
- I use `COPYING` as the template license file, [which is ignored in `copier.yml`](https://github.com/Tecnativa/doodba-copier-template/blob/339d9589a2213e521a2a85b174b51b3bfdf23513/copier.yml#L21).
- I use [a templated `{% if project_license %}LICENSE{% endif %}.jinja` file](https://github.com/Tecnativa/doodba-copier-template/blob/339d9589a2213e521a2a85b174b51b3bfdf23513/%7B%25%20if%20project_license%20%25%7DLICENSE%7B%25%20endif%20%25%7D.jinja) for subprojects licenses, depending on user choice.

So, while I agree this is a valid feature request, I just wanted to show you how this problem could be fixed today.

In case we add this feature, a new automatic key should be added to `.copier-answers.yml` to specify the subdir.

**Comment by pawamoy** [comment]
Thanks @Yajo!

That's a nice way of rendering the license file, I'll keep that in mind.

I'd still definitely prefer not mixing up files that are meant to be rendered as part of the generated project with "meta" files.

If I can help implementing this subdirectory feature, just let me know :slightly_smiling_face:

**Comment by Yajo** [comment]
> If I can help implementing this subdirectory feature, just let me know slightly_smiling_face

Yes, just open a PR and we'll review. :wink:
