### ISSUE TITLE
Tasks and migrations documentation

### ISSUE THREAD

**Issue by pawamoy** [pykong/copier#195]
I thought tasks would only be run once, when generating the project the first time.

Description of tasks and migrations could be improved a bit:

```
# Commands to be executed after the copy
```

- not just after a copy: after generating or updating a project, i.e. always

```
# They have the $STAGE=task environment variable
```

- no example of use of this `STAGE` variable

```
# Migrations are like tasks, but they are executed:
# - Evaluated using PEP 440
```

- what's that :grin:? I'm trying to read the [PEP 440 page](https://www.python.org/dev/peps/pep-0440/), but it's really long! In what way does it affect migrations runs?

```
# - In the same order as declared here
```

- aren't tasks executed in the same order as declared as well?

```
# - Only when new version >= declared version > old version
# - Only when updating
# - After being rendered with the same renderer as the rest of the template
```

- isn't it the same for tasks? also, what does "being rendered" mean? we're speaking of the migration command (the string) I guess

```
# - With the same supported syntaxes as `_tasks`, above
```

- this line could be removed, or the `but` in `Migrations are like tasks, but they are executed:` should be removed instead.

```
# - With $VERSION_FROM, $VERSION_TO and $VERSION_CURRENT, $STAGE (before/after)
#   environment variables
```

- could be nice to have examples for these variables as well! also, `and` is misplaced, or another should be added before `$STAGE`

**Comment by Yajo** [comment]
Yikes, indeed docs are misleading. Thanks!

> what's that grin? I'm trying to read the [PEP 440 page](https://www.python.org/dev/peps/pep-0440/), but it's really long! In what way does it affect migrations runs?

I opened #199 and #200, where you might consider contributing if you wish :blush:
