### ISSUE TITLE
Assert minimal copier version

### ISSUE THREAD

**Issue by Yajo** [pykong/copier#198]
The template needs a new key:

```yaml
# copier.yml
_min_copier_version: v3.1.0
```

Otherwise the template might fail badly if a template is done for a version that i.e. includes #190 and is executed under a copier that doesn't have it.

@pawamoy You might be interested in this.

**Comment by pawamoy** [comment]
Yes, good catch, displaying a warning when the version is too low is way better than starting to generate and fail.

**Comment by Yajo** [comment]
I'd say an error more than a warning... If the templater took the time to write this constraint, it's better to enforce it.

**Comment by pawamoy** [comment]
Unfortunately, I don't think it will be possible to write tests for that, because `poetry-dynamic-versioning` does not work with `poetry run`, and so we'll not be able to retrieve the current version to compare it to a `_min_copier_version`.

**Comment by Yajo** [comment]
Mock it:

- https://docs.python.org/3/library/unittest.mock.html#unittest.mock.patch
- https://docs.pytest.org/en/latest/monkeypatch.html
