### ISSUE TITLE
Sharing identical files between templates

### ISSUE THREAD

**Issue by pykong** [pykong/copier#67]
I share many identical files between different template folders.
I'd really like to keep my templates DRYer and include those files by reference only.

@jpscaletti
Do you get an idea of how we could achieve this?

_Some ideas:_
- We allow for a multi-level inheritance whereby a template folder inherits templates from a parent template.
- We allow specifying folder whose contents or a list of file paths to be copied over to the destination folder.

Relates to: #58

**Comment by jpscaletti** [comment]
A soft link? Copy & Paste? The inheritance system for templates sounds like over-engineering it to me.

**Comment by jpscaletti** [comment]
I was writing that Jinja's inheritance mechanism doesn't work with files outside the templates folder, but I just remembered the one of Jinja's loader allows you to specify several folders as sources...

So yes, in theory, we could use Jinja's [ChoiceLoader](https://jinja.palletsprojects.com/en/2.10.x/api/#jinja2.ChoiceLoader) or maybe a [PrefixLoader](PrefixLoader) by default and have a list of optional "extra templates folders" in the `copier.yml` file to add to the current working folder (added by default). In that way, you could call a group of templates to use however you want.

How it's sound to you?

**Comment by pykong** [comment]
Thanks for your answer. You appear to a have much more knowledge about Jinja2's engine than me.
Let me try to translate your suggestions into code. Should be ready by the weekend.

My suggestion is that once we merge (or reject) the **PR** resulting from that you may release `copier 3`.

**Comment by pykong** [comment]
I wonder if we couldn't just:
- provide a list of additional source folder paths
- iterate over this list against `copy_local`

We would need to define an order of precedence within that list and versus the original `src_path` setting.

I am still researching whether using Jinja2's ChoiceLoader would offer any benefits.
As far as my current understanding goes ChoiceLoader would only provide additional lookup paths for templates but not instructable to include additional folders.

**Comment by pykong** [comment]
I believe we were talking about different things.

**You**: How to teach Jinja2 to locate additional files...
**Me**: How can we keep our templates DRY...

We can already specify additional lookup paths via the `extra_paths` setting.
Yet, this is only "half-DRY" as we include file content from another location but would still require to do so in an `*.tmpl` file. Hence we may need to include a lot of the same of those files in multiple templates. Not exactly DRY.

Nevermind I have an elegant idea on how to address this.
I am prototyping this idea right now. If it works as robustly as I am imaging `copier` will be endowed with a new and very powerful feature right in time before its version 3. ;-)

**Comment by pykong** [comment]
This is issue is no longer relevant.
