### ISSUE TITLE
Repository transfer name collision with fork.

### ISSUE THREAD

**Issue by pykong** [pykong/copier#83]
@jpscaletti 

I have renamed my own copier fork to `pykong:copier_fork` in an attempt to circumvent the name collision whilst keep the open PR #79 alive.

Please have another try at transfering.

**Comment by jpscaletti** [comment]
It didn't work,  GitHub still knows it's a fork and fails :(

<img width="563" alt="nope" src="https://user-images.githubusercontent.com/31000/66326953-8f44f680-e8ef-11e9-926b-60c9e12224b0.png">

I think you should go old-school and
1. checkout your fork in the work-in-progress PR branch
2. delete the fork in GitHub
3. clone the new repo **in a new folder**
4. create a new `folder_inheritance` branch in the new repo
5. copy&paste the work-in-progress code for the first folder to the new folder
6. commit & push that work-in-progress code to the `folder_inheritance` branch

**Comment by pykong** [comment]
@jpscaletti 

OK. It was worth a try.
Old school then.

I have deleted `pykong:copier_fork`.
The remaining **PR 79** is now listed to stem from an unknown repository.
(So far for exploring the darkest recesses of GitHub. ;-) )

**Comment by pykong** [comment]
This time it worked. ;-)
