### ISSUE TITLE
Transfer: How to link PyPI?

### ISSUE THREAD

**Issue by pykong** [pykong/copier#84]
@jpscaletti 

How do we fare about the uplink of this repo to PyPI?
After all, people will want to be able to install `copier` via `pip` I presume.

Do you have got any idea/instructions on that part of the transfer?

**Comment by pykong** [comment]
@jpscaletti Whilst I co-maintain packages listed on PyPI this is going to my first own package there.
I am going to open an account and let you know. 

I am busy right now but I will do it no later than Sunday.

**Comment by jpscaletti** [comment]
Sure, just let me know.

**Comment by pykong** [comment]
I a have just opened an account on PyPI: 
https://pypi.org/user/pykong/

**Comment by jpscaletti** [comment]
Congrats 🎉  You are now the owner.
You can remove me now (I can't remove myself).

**Comment by pykong** [comment]
Got the project on PyPI. I have removed you.
Closing this issue.

Thanks!
