### ISSUE TITLE
Transfer - Relationship with mastermold

### ISSUE THREAD

**Issue by pykong** [pykong/copier#85]
@jpscaletti 

Admittedly, I do not understand what `mastermold` is.
How is it related to `copier`?
What is the `mm.py` file for?

**Comment by jpscaletti** [comment]
It's unnecessary now, especially because this project has different defaults, like mypi.
I wrote about it here: https://jpscaletti.com/master-mold-for-python-packages/

**Comment by pykong** [comment]
`mm.py` got removed via ced4284
