### ISSUE TITLE
Add CONTRIBUTORS.md

### ISSUE THREAD

**Issue by pykong** [pykong/copier#86]
To honor the diligent contributors of this project it is a tradition to list their names in a special file.

A special mention would, of course, go to @jpscaletti as the original author of this project without his diligence and vision `copier` would not be a thing right now.
@jpscaletti if you do not object I am going to have your name listed there.

**Comment by jpscaletti** [comment]
😄

**Comment by pykong** [comment]
`pydantic` converts that emoji to `True`.

So, I assume this means yes.

**Comment by jpscaletti** [comment]
Yes, of course. That would be nice.

**Comment by pykong** [comment]
I am going to add a section in the readme.
For now, we do not have that many contributors, requiring a separate file.
And the README is a more prominent place to honor the original work of jpscaletti.

See: #87
