### ISSUE TITLE
Copy updates as 1st-class citizens

### ISSUE THREAD

**Issue by Yajo** [pykong/copier#88]
The scaffolding landscape in Python currently is pretty bad, thanks for bringing to life this nice project.

Handling updates is pretty bad still. Imagine:

1. You have a scaffolding. 
1. You copy it and start a new project.
1. Your new project evolves in a separate git repo.
1. You update your scaffolding.
1. You want to apply your scaffolding to your copied project again, but don't want the default answers; you want the ones you used last time.
1. You don't want the updates to touch the files that you already touched, unless they've been touched also in those lines in the source scaffolding.

[`cruft`](https://github.com/timothycrosley/cruft/) handles this pretty well, as it stores all answers in a json file, which also happens to include the git commit of the source when it was copied, and this allows it to extract the diff since that commit to the latest and apply only that diff to the destination.

**How should `copier` *copy* (lol) this behavior?**

First, when copying:

1. When a scaffolding is copied, store all answers in a file. It could be something like `.copied.yml`.
1. Store in `.copied.yml` also the source of the copy (e.g. `_copied_from: gh:my/scaffolding`).
1. When the scaffolding was a git repo, store also the copied commit. It could be a hidden key in `.copied.yml` (e.g.: `_copied_commit: o3ho4ho5hoho2hoh2o`).

Then, support running `copier` without arguments, which:

1. Fails if `.copied.yml` is absent.
1. Fails if `_copied_from` is absent in that file.
1. If `_copied_commit` is absent, it should be the equivalent of `copier $_copied_from .`.
1. If `_copied_commit` is present, it should be the equivalent of `copied --from-commit $_copied_commit --to-commit HEAD $_copied_from .`.

As you probably have guessed, we need to add new flags `--from-commit` and `--to-commit` (which defaults to `HEAD`), which:

1. Fails if source is not a git repo.
1. If present, will generate a patch from `--from-commit` to `--to-commit`.
1. It will only apply that diff.
1. Does nothing if both flags are equal.

**Why all of this?**

1. We need to be able to just execute `copier` in a pre-copied scaffolding and let it get only the diff since it was copied last time.
1. We need to be able to ensure a project is updated with its scaffolding, i.e. to raise an error in CI when that's not the case.

**Comment by pykong** [comment]
@Yajo 
Thanks for your note and all the input provided!
Indeed your input is very welcome as I do not know how others are using it.
Feedback is vital so I can better decide what to improve.

However, it will take many weeks until I am releasing the next major version. I am going back to your threads before my next coding burst.

> The scaffolding landscape in Python currently is pretty bad, thanks for bringing to life this nice project.

Huh, isn't there the almighty `cookiecutter` that everyone seems to use? Why would you prefer `copier` over other templating engines?

Further: If you like `copier` then you may _star_ or even vote for it to join the python awesome list:
[here](https://github.com/vinta/awesome-python/pull/1350)

**Comment by Yajo** [comment]
>  Thanks for your note and all the input provided!
>  Indeed your input is very welcome as I do not know how others are using it.
> Feedback is vital so I can better decide what to improve.

Thank's, I'm glad you like it. :blush: 

I like very much the approach of this project, and I've seen it's being actively developed, so I wanted to give some good suggestions.

My specific use case is that in my company we maintain [this public scaffolding](https://github.com/Tecnativa/doodba-scaffolding), which is a template for projects based on our Odoo devops platform  [Doodba](https://github.com/Tecnativa/doodba). We also maintain a private scaffolding based on that public one, with some more thingies in it.

[Its first commit is from 2017](https://github.com/Tecnativa/doodba-scaffolding/commit/d708c740af99762a1b035cec1d087accfefd0bed) and we've been actively maintaining it since then. Ourselves and many other companies I know use this scaffolding to maintain many projects. We have a lot of them, and each project is for one customer, and it has that full git history you see there, plus customer customizations.

Back in 2017 I didn't find a scaffolding tool that matched all of our requirements for updating the scaffolding, and I decided to just add one git repo that would be cloned many times. As of today, copying that scaffolding for us is just `git clone`, and updating from it is just `git pull scaffolding master` in your "other" copy.

Now we're revisiting the subject because we need to support a broader amount of doodba versions, and a proper scaffolding tool would really help in that sense. 2 years later, the same issues that blocked me from choosing a scaffolding tool remain open.

In the past, I have seen myself having to update 30 projects just because one update from that scaffolding just _had_ to be applied. It's a tedious manual process. A scaffolding tool with good day 2 support and CI-friendly would save hours there.

> > The scaffolding landscape in Python currently is pretty bad, thanks for bringing to life this nice project.
> 
> Huh, isn't there the almighty `cookiecutter` that everyone seems to use? Why would you prefer `copier` over other templating engines?

I said it's pretty bad because cookiecutter is basically the only serious option. Other options are just [mr.bob](https://github.com/domenkozar/mr.bob), with its latest commit dating 2017 (and way uglier templates), and other tiny projects that use cookiecutter and workaround its issues, such as cruft.

However, when it comes to template and project maintenance, with cookiecutter:

1. Templates use JSON, written by hand. :nauseated_face:  https://github.com/cookiecutter/cookiecutter/issues/970
1. #89 happens too: https://github.com/cookiecutter/cookiecutter/issues/794
1. Current issue is there too: https://github.com/cookiecutter/cookiecutter/issues/235

I have tested even yeoman, which is today's (and 2017's) most supported scaffolding tool available, but its updating system is also not good. At least not as good as cruft's, and not as good as to justify the complexity of a yeoman generator.

Cruft does it fine, although it's just one of those many projects that aim to workaround cookiecutter's problems instead of just fixing them there. I guess that comes from the fact that cookiecutter isn't actively developed. :man_shrugging: 

I found copier to be simpler, and I like its templates and the colorful report that tells what has changed and what not. I like how it just "copies" directories. It also expands templates and reports in a more CI-friendly way what has been updated from the origin.

However copier lacks the same as all scaffolding tools except cruft: forgets about day 2.

I was about to give it all away and just use cruft, but I'd really love to have one single tool where project maintenance is as important as project bootstrapping. Copier is lovely, and simpler; I love its simplicity. Also copier uses YAML, which is much richer and comfortable to use than JSON.



> Further: If you like `copier` then you may _star_ or even vote for it to join the python awesome list:

I'd do that when copier fixes this issue, #89 and #90. Then copier will be simply the best scaffolding tool in the planet. It will _really_ have a big advantage over other tools.

**Comment by pykong** [comment]
| I'd do that when copier fixes this issue, #89 and #90. Then copier will be simply the best scaffolding tool in the planet. It will really have a big advantage over other tools.

That is quite a goal to strive for. :-)

I am try to start a new development sprint in December.
Then I am going to attend to all the tickets.

**Comment by Yajo** [comment]
Cool, I have a PR in the oven ready to improve this. I think tomorrow I'll have time to push it.

**Comment by Yajo** [comment]
So all pieces are in place for the last PR about this. I'm thinking about how it should be done. Let me know what you think:

When the user runs `copier update`:

1. Clone template in a temporary folder, updated to latest commit.
1. `cd /tmp/that-temporary-folder` (so to speak)
1. Checkout the commit that was stored in `.copier-answers.yml`.
1. Fill the template with data from `.copier-answers.yml`.
1. Commit that with `--author Copier`. COMMIT_1
1. Checkout the last commit.
1. Ask the user for answers (if answer exists in `.copier-answers.yml`, that'd be the default value; otherwise, the default value would be the one specified in the template).
1. Fill the template with new answers.
1. Commit that also with  `--author Copier`. COMMIT_2
1. Extract diff from COMMIT_1...COMMIT_2
1. `cd $destination_dir` (so to speak)
1. Apply extracted diff.
1. Store the new base commit into `.copier-answers.yml`

This way, the user would only get the updated diff from the template, and in case there are any conflicts, the user could use normal diff resolution tools (`git difftool` for example) to resolve them.

More ideas:

1. A `--commit` flag to autocommit if there are changes and no conflicts?
1. A `--no-diff` flag to skip this? Or maybe just repeat the original `copier copy template destination` command for that?

**Comment by pykong** [comment]
@Yajo. The approach seems sane to me. The `--commit` flag as well.
I am not yet sure about the `--no-diff`` flag. 

Maybe put `--no-diff` into a separate **PR**.

Otherwise feel free to go ahead. Thanks for the great work! I really appreciate it.

btw - do you use https://gitter.im/ ?

**Comment by Yajo** [comment]
> btw - do you use https://gitter.im/ ?

Never tried.
