### ISSUE TITLE
Prompt self-templating

### ISSUE THREAD

**Issue by Yajo** [pykong/copier#90]
We need to go from:

```yml
# copier.yml
smtp_host: example.com
smtp_user: postmaster@example.com
```

To: 

```yml
# copier.yml
smtp_host: example.com
smtp_user: postmaster@[[smtp_host]]
```

**Comment by pykong** [comment]
Makes total sense to have it. This feature would make a nice addtion to `copier`.

**Comment by pykong** [comment]
The issue with that example config file is that it does not represent valid yaml.

"["  is a character that cannot start any token

While I still agree that the feature you are asking for is very much desirable, I believe it would be very hard to implement.

**Comment by Yajo** [comment]
No, this is missing still. I noticed the description was misleading so I updated the example. It makes sense now 🤣

**Comment by Yajo** [comment]
I moved this to next milestone, v3 seems ready to go for me.

**Comment by pawamoy** [comment]
I'd like to work on this, could you give me hints?

**Comment by pawamoy** [comment]
I guess the `default` value must be rendered using the previous answers in `query_user_data`?

**Comment by Yajo** [comment]
I bet you'd have to create a new env for each loop, because the values would differ as the user keeps answering.

In any case, you have to at least create a new temporary env, because the normal env is not created until we have all answers in place, and at this point we still don't have them.

Also you shouldn't just render `default` but all values in the question dict: `default`, `help` and maybe even `choices` (key and value in this case, if it's a dict).

One thing you have to think is that there could be templating errors if one answer is not yet given while asking the previous one.

You can take a look at #161 also, which depends on this one and shouldn't be very hard to implement once this is fixed.

:thinking: This is trickier than it seems, but your help will be very appreciated! :blush: :raised_hands:

**Comment by pawamoy** [comment]
> I bet you'd have to create a new env for each loop, because the values would differ as the user keeps answering.

I don't think so. You don't need a new env when the context changes. The env just contains the filters, some configuration, and templates loader (and in this case templates are strings). At each iteration, new values are added to `results` and these values are used as context to render the values for the next iteration.

> In any case, you have to at least create a new temporary env, because the normal env is not created until we have all answers in place, and at this point we still don't have them.

OK!

> Also you shouldn't just render default but all values in the question dict: default, help and maybe even choices (key and value in this case, if it's a dict).

Makes sense, I will try :slightly_smiling_face: 

> One thing you have to think is that there could be templating errors if one answer is not yet given while asking the previous one.

I guess it's the user responsibility to write their `copier.yml` fields in the right order. We could indeed print a warning if the value is templated but was not rendered.

**Comment by Yajo** [comment]
> I guess it's the user responsibility to write their `copier.yml` fields in the right order.

I agree.

> We could indeed print a warning if the value is templated but was not rendered. Not sure if there's a Jinja method allowing to tell if a string is "templated" or not.

That'd be nice. Gotta see if Jinja allows that. Otherwise, an exception would be acceptable for what you said before.

**Comment by pawamoy** [comment]
> Otherwise, an exception would be acceptable for what you said before.

Oh silly me. In strict mode, if the string cannot be rendered (due to variables not being defined or else), it will trigger an exception. That's how we'll know. For some reason when writing this I was thinking that, if the string couldn't be rendered, it would be returned as-is, but it's not true. Instead it would be returned empty (or partially empty), and that would be hard to detect.

Strict mode it is!

**Comment by Yajo** [comment]
> And catch the exception to abort and print a readable warning?

Just reraise it as `copier.config.objects.UserMessageError` and it should be enough.
