### ISSUE TITLE
Copier should autoignore files if a .tmpl-suffixed one exists

### ISSUE THREAD

**Issue by Yajo** [pykong/copier#91]
This terminal session shows the problem:

```
root@6d41e6e965f0:~# ls template/
README.md  README.md.tmpl
root@6d41e6e965f0:~# cat template/README.md
1
root@6d41e6e965f0:~# cat template/README.md.tmpl 
2
root@6d41e6e965f0:~# copier template/ copy

    create  README.md
  conflict  README.md
 Overwrite /root/copy/README.md? [Y/n] y
     force  README.md
```

As the template has both `README.md` and `README.md.tmpl` files, there will *always* be a conflict.

`README.md` should be ignored always, automatically.

If this were supported, it would be very helpful for cases like README files, where your template might have a README which is different from the README that will be generated in the copy. The same goes for files such as `.gitlab-ci.yml`, `.travis.yml`, `.pre-commit.yml`, etc.

---

~~Workaround: add this `copier.yml`:~~

```yaml
_exclude:
  - README.md
```

Nope, the workaround doesn't work. It doesn't detect changes when copying the 2nd time.

**Comment by pykong** [comment]
Thank you for all your notes. They're warmly welcome.
I am not commenting on their content right now, but be assured I will consider all of them for my next development sprint.
