### ISSUE TITLE
New name for this project?

### ISSUE THREAD

**Issue by pykong** [pykong/copier#97]
It went from formerly `voodoo` to now `copier`.

- Can we come up with an even shorter name = less typing?
- What name would better reflect the function not only *copying* templates but render them with actual customization?

### List of suggestions:
- `spark`
- `clay` (already taken ;-))
- `cast`
- `mold`
- `cook`

**Comment by Yajo** [comment]
I like `copier`. :blush:

**Comment by pykong** [comment]
OK. Decided. We are going to stay with `copier` then. 😺
